"""Builder for the brain artifact deployment_architecture.json.

Scans the live on-disk tree and produces a `DeploymentCollection` whose
`files[]` enumerates every file each target ships. Each entry carries a
`disposition` of either:

  - 'managed'    — JSON owns the bytes verbatim in embedded_content.
                   Dockerfiles and GitHub Actions workflow YAMLs only,
                   per the operator compromise.
  - 'referenced' — only source_location is captured; embedded_content
                   is None. Deploy machinery copies bytes from
                   origin/<branch>'s tree at deploy time.

Binary content (when managed) is base64-encoded and prefixed with
`__base64__:` so the schema sees a string and the Extractor can
faithfully restore the raw bytes.

Move detection (V18 compliance — JSON is the truth, substrate keeps
disk consistent): after enumerating, the Builder scans every managed
file's embedded_content for path-like substrings. Each substring is
checked against the universe of source_locations in the current
collection (truth). If a substring is path-shaped but not a current
source_location, the Builder looks up its basename in the collection.
If the basename resolves to exactly one current source_location, the
substring is rewritten to that new path inside embedded_content AND
the disk copy of the managed file is updated so source_location bytes
match. Ambiguous matches (zero or >1 candidate) are left alone here;
Crosswalk surfaces them.
"""
from __future__ import annotations

import base64
import re as _re
from pathlib import Path
from typing import Iterable

from target_record import (
    DeploymentCollection,
    EnvironmentBinding,
    FileComposition,
    TargetRecord,
)


_FEATURE_ID: str = "EPIC-008-F-012"
_BASE64_PREFIX: str = "__base64__:"

# disposition is 'managed' only for files whose bytes the JSON owns
# verbatim per the operator compromise: Dockerfile + workflow YAML.
_MANAGED_HANDLER_TYPES: frozenset[str] = frozenset({"dockerfile", "workflow_yaml"})

# Standard exclude set applied to every directory walk. Workflow rsync
# uses the same skip set (__pycache__, *.pyc, .env). Build outputs and
# caches are also dropped so the brain artifact reflects source, not
# generated bytes.
_EXCLUDE_DIRS: frozenset[str] = frozenset({
    "__pycache__",
    "node_modules",
    "dist",
    ".pytest_cache",
    ".vite",
    "bin",
    "obj",
    "out",
    ".git",
})
_EXCLUDE_FILE_NAMES: frozenset[str] = frozenset({".env", ".DS_Store"})
_EXCLUDE_FILE_SUFFIXES: frozenset[str] = frozenset({".pyc", ".pyo"})


def _classify_handler(rel_posix: str, name: str) -> str:
    """Map a file to one of the schema's closed handler_type enums."""
    if name == "Dockerfile":
        return "dockerfile"
    if rel_posix.startswith(".github/workflows/") and (
        name.endswith(".yml") or name.endswith(".yaml")
    ):
        return "workflow_yaml"
    if name == "requirements.txt":
        return "python_requirements"
    suffix = Path(name).suffix.lower()
    if suffix == ".py":
        if name.startswith("test_") or name.endswith("_test.py") or "/tests/" in rel_posix:
            return "python_test"
        return "python_source"
    if suffix == ".sh":
        return "shell_script"
    if suffix == ".bat":
        return "bat_script"
    if suffix == ".md":
        return "markdown"
    if suffix in (".json", ".jsonl"):
        return "json"
    if suffix in (".crt", ".key", ".csr", ".pem", ".srl"):
        return "cert_or_key"
    # Everything else (.tsx, .ts, .css, .html, .svg, .png, .pdf, .txt, etc.)
    return "static_asset"


def _disposition_for(handler_type: str) -> str:
    return "managed" if handler_type in _MANAGED_HANDLER_TYPES else "referenced"


def _read_managed_content(abs_path: Path) -> str:
    """Capture bytes for a managed file as a schema-compatible string.

    Try utf-8 strict decode; on failure base64-encode and prefix. Any
    I/O error raises.
    """
    raw = abs_path.read_bytes()
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError:
        return _BASE64_PREFIX + base64.b64encode(raw).decode("ascii")
    if text.encode("utf-8") != raw:
        return _BASE64_PREFIX + base64.b64encode(raw).decode("ascii")
    return text


def _rel_posix(repo_root: Path, abs_path: Path) -> str:
    return abs_path.relative_to(repo_root).as_posix()


def _walk(
    repo_root: Path,
    dir_rel: str,
    extra_exclude_rel_prefixes: Iterable[str] = (),
) -> list[Path]:
    """Walk repo_root/dir_rel, yielding regular files in deterministic
    order, respecting the standard exclude set plus any extra rel-path
    prefixes the caller wants dropped (e.g., the pre-built React dist
    that lives under backend/static/).
    """
    root = repo_root / dir_rel
    if not root.is_dir():
        raise FileNotFoundError(
            f"Builder expected directory at {root}; absent on disk"
        )
    extra = tuple(p.replace("\\", "/").rstrip("/") for p in extra_exclude_rel_prefixes)
    out: list[Path] = []
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        parts = set(path.parts)
        if parts & _EXCLUDE_DIRS:
            continue
        if path.name in _EXCLUDE_FILE_NAMES:
            continue
        if path.suffix.lower() in _EXCLUDE_FILE_SUFFIXES:
            continue
        rel = _rel_posix(repo_root, path)
        if any(rel == p or rel.startswith(p + "/") for p in extra):
            continue
        out.append(path)
    return out


class Builder:
    """Builds a `DeploymentCollection` by scanning the live tree."""

    def __init__(self) -> None:
        self._unclassified: list[str] = []

    def unclassified(self) -> list[str]:
        return list(self._unclassified)

    def build_collection(self, repo_root: Path) -> DeploymentCollection:
        repo_root = repo_root.resolve()
        coll = DeploymentCollection()
        coll.add(self._build_workflow_runner(repo_root))
        coll.add(self._build_hf_space_findcare_backend(repo_root))
        coll.add(self._build_hf_space_evaluatecare_backend(repo_root))
        coll.add(self._build_hf_space_shared_services(repo_root))
        coll.add(self._build_cloudflare_pages_website(repo_root))
        coll.add(self._build_host_local_deploy_tool(repo_root))
        # V18 compliance: scan every managed file's embedded_content
        # for path-shaped substrings that look like repo-source paths
        # (first segment is a current top-level source_location dir)
        # but don't match any current source_location. For each, if
        # the basename uniquely matches one current source_location,
        # rewrite the substring to that path. Runtime paths like
        # "hf_space/README.md" or "/tmp/foo" are blocked because their
        # first segment isn't a repo top-level dir.
        self._rewrite_stale_path_refs_in_managed_files(coll)
        return coll

    # Regex for a repo-relative path: at least one slash, only
    # path-safe chars, ends in a token that may contain a dot. Won't
    # match URLs (no `://`) or windows-style backslash paths.
    _PATH_RE = _re.compile(
        r"(?<![A-Za-z0-9_/.\\:])"        # boundary on left (no ident/path char)
        r"([A-Za-z_][\w.-]*"             # first segment
        r"(?:/[\w.-]+)+)"                # one or more /segment
        r"(?![A-Za-z0-9_/.])"            # boundary on right
    )

    @classmethod
    def _rewrite_stale_path_refs_in_managed_files(
        cls,
        coll: DeploymentCollection,
    ) -> None:
        """Scan-based stale path rewrite, gated by top-dir whitelist.

        For each managed file's embedded_content, extract every
        path-shaped substring (per _PATH_RE). A substring is eligible
        for rewrite only if its first segment is one of the current
        top-level source_location dirs (e.g., 'Code', 'architecture',
        'Website', 'DevOps', '.github'). If eligible AND the substring
        is not itself a current source_location AND its basename
        uniquely matches one current source_location, rewrite to that
        new path. The top-dir gate is what prevents runtime paths
        ('hf_space/README.md', '/tmp/...') from matching.

        The JSON is updated; disk is the downstream — the caller
        runs Extractor.materialize_collection to push managed bytes.
        """
        valid: set[str] = set(coll.all_source_locations())
        repo_top_dirs: set[str] = {
            s.split("/", 1)[0] for s in valid if "/" in s
        }
        by_basename: dict[str, list[str]] = {}
        for s in valid:
            base = s.rsplit("/", 1)[-1]
            by_basename.setdefault(base, []).append(s)

        def _maybe(m: _re.Match[str]) -> str:
            p = m.group(1)
            if p in valid:
                return p  # already correct
            first_seg = p.split("/", 1)[0]
            if first_seg not in repo_top_dirs:
                return p  # runtime path or external — leave alone
            base = p.rsplit("/", 1)[-1]
            candidates = by_basename.get(base, [])
            if len(candidates) == 1:
                return candidates[0]
            return p

        for record in coll:
            for f in record.files:
                if f.disposition != "managed" or f.embedded_content is None:
                    continue
                if f.embedded_content.startswith(_BASE64_PREFIX):
                    continue
                new_text = cls._PATH_RE.sub(_maybe, f.embedded_content)
                if new_text != f.embedded_content:
                    f.embedded_content = new_text

    @staticmethod
    def _compose_file(repo_root: Path, abs_path: Path) -> FileComposition:
        rel = _rel_posix(repo_root, abs_path)
        name = abs_path.name
        handler = _classify_handler(rel, name)
        disposition = _disposition_for(handler)
        embedded: str | None = None
        if disposition == "managed":
            embedded = _read_managed_content(abs_path)
        return FileComposition(
            feature_id=_FEATURE_ID,
            source_location=rel,
            handler_type=handler,
            disposition=disposition,
            embedded_content=embedded,
        )

    def _enumerate(
        self,
        repo_root: Path,
        dir_rels: Iterable[str],
        extra_exclude_rel_prefixes: Iterable[str] = (),
    ) -> list[FileComposition]:
        files: list[FileComposition] = []
        seen: set[str] = set()
        excl = list(extra_exclude_rel_prefixes)
        for d in dir_rels:
            for path in _walk(repo_root, d, excl):
                rel = _rel_posix(repo_root, path)
                if rel in seen:
                    continue
                seen.add(rel)
                files.append(self._compose_file(repo_root, path))
        # Stable deterministic order by source_location.
        files.sort(key=lambda f: f.source_location)
        return files

    def _build_workflow_runner(self, repo_root: Path) -> TargetRecord:
        files = self._enumerate(repo_root, [".github/workflows"])
        addr = "github.com/ChatHealthy/repo/actions"
        envs = [
            EnvironmentBinding(env_binding="local", node_address=addr),
            EnvironmentBinding(env_binding="dev", node_address=addr),
            EnvironmentBinding(env_binding="qa", node_address=addr),
            EnvironmentBinding(env_binding="prod", node_address=addr),
        ]
        return TargetRecord(
            target_id="target_workflow_runner_github_actions",
            target_kind="github_actions_workflow_runner",
            environments=envs,
            files=files,
        )

    def _build_hf_space_findcare_backend(
        self, repo_root: Path
    ) -> TargetRecord:
        envs = [
            EnvironmentBinding(
                env_binding="dev",
                node_address="dev.chathealthy.ai/findcare",
            ),
            EnvironmentBinding(
                env_binding="qa",
                node_address="qa.chathealthy.ai/findcare",
            ),
            EnvironmentBinding(
                env_binding="prod",
                node_address="chathealthy.ai/findcare",
            ),
        ]
        # rsync source dirs (mirrors the existing workflow YAML's rsyncs).
        # Excludes drop generated dirs (React static/, frontend dist/,
        # node_modules/) so the brain artifact reflects source, not
        # build output. The deploy runs npm build during materialize.
        files = self._enumerate(
            repo_root,
            [
                "Code/ConversationalUX/FindCareChat/backend",
                "Code/ConversationalUX/FindCareChat/frontend",
                "Code/Shared",
                "brain/machine_artifacts/content",
                "Code/ConversationalUX/ChatHealthyWhoAmIChat/me",
                "FrontEndApplicationLib",
                "FindCare",
                "DevOps/FindCareBackend",
            ],
            extra_exclude_rel_prefixes=[
                "Code/ConversationalUX/FindCareChat/backend/static",
                "Code/ConversationalUX/FindCareChat/frontend/dist",
            ],
        )
        return TargetRecord(
            target_id="target_hf_space_findcare_backend",
            target_kind="hf_space",
            environments=envs,
            files=files,
        )

    def _build_hf_space_evaluatecare_backend(
        self, repo_root: Path
    ) -> TargetRecord:
        envs = [
            EnvironmentBinding(
                env_binding="dev",
                node_address="dev.chathealthy.ai/evaluatecare",
            ),
            EnvironmentBinding(
                env_binding="qa",
                node_address="qa.chathealthy.ai/evaluatecare",
            ),
            EnvironmentBinding(
                env_binding="prod",
                node_address="chathealthy.ai/evaluatecare",
            ),
        ]
        files = self._enumerate(
            repo_root,
            ["evaluateCare/Code", "FrontEndApplicationLib"],
        )
        return TargetRecord(
            target_id="target_hf_space_evaluatecare_backend",
            target_kind="hf_space",
            environments=envs,
            files=files,
        )

    def _build_hf_space_shared_services(self, repo_root: Path) -> TargetRecord:
        envs = [
            EnvironmentBinding(
                env_binding="dev",
                node_address="dev.chathealthy.ai/sharedservices",
            ),
            EnvironmentBinding(
                env_binding="qa",
                node_address="qa.chathealthy.ai/sharedservices",
            ),
            EnvironmentBinding(
                env_binding="prod",
                node_address="chathealthy.ai/sharedservices",
            ),
        ]
        files = self._enumerate(
            repo_root,
            ["sharedServices/Code", "FrontEndApplicationLib"],
        )
        return TargetRecord(
            target_id="target_hf_space_shared_services",
            target_kind="hf_space",
            environments=envs,
            files=files,
        )

    def _build_host_local_deploy_tool(
        self, repo_root: Path
    ) -> TargetRecord:
        """The deploy substrate + smoke test infrastructure that runs
        on the operator's local host. Not shipped to any remote target;
        enumerated so its files live inside the JSON's universe of
        source_locations. The substrate's own directory is discovered
        from this Builder module's own __file__ — so if the substrate
        is moved to a different parent dir, no Python edit is needed:
        Builder rediscovers its own dir on the next run.
        """
        envs = [
            EnvironmentBinding(env_binding="local", node_address="localhost/deploy_substrate"),
        ]
        substrate_dir_rel = Path(__file__).resolve().parent.relative_to(repo_root).as_posix()
        files = self._enumerate(repo_root, [substrate_dir_rel])
        return TargetRecord(
            target_id="target_host_local_deploy_tool",
            target_kind="host_os_process",
            environments=envs,
            files=files,
        )

    def _build_cloudflare_pages_website(
        self, repo_root: Path
    ) -> TargetRecord:
        envs = [
            EnvironmentBinding(env_binding="dev", node_address="dev.chathealthy.ai"),
            EnvironmentBinding(env_binding="qa", node_address="qa.chathealthy.ai"),
            EnvironmentBinding(env_binding="prod", node_address="chathealthy.ai"),
        ]
        files = self._enumerate(repo_root, ["Website"])
        return TargetRecord(
            target_id="target_cloudflare_pages_website",
            target_kind="cloudflare_pages_project",
            environments=envs,
            files=files,
        )
