"""Builder for the brain artifact deployment_architecture.json.

Scans the live on-disk tree and produces a `DeploymentCollection` whose
`files[]` enumerates every file each target ships. Each entry carries a
`disposition` of either:

  - 'managed'    — JSON owns the bytes verbatim in embedded_content.
                   Dockerfiles only, per the operator compromise.
  - 'referenced' — only source_location is captured; embedded_content
                   is None. Deploy machinery copies bytes from
                   origin/<branch>'s tree at deploy time.

Binary content (when managed) is base64-encoded and prefixed with
`__base64__:` so the schema sees a string and the Extractor can
faithfully restore the raw bytes.

Move detection (V18 compliance — JSON is the truth, substrate keeps
disk consistent): after enumerating, the Builder scans every managed
file's embedded_content for path-like substrings. Each substring is
checked against the universe of source_locations in the current
collection (truth). If a substring is path-shaped but not a current
source_location, the Builder looks up its basename in the collection.
If the basename resolves to exactly one current source_location, the
substring is rewritten to that new path inside embedded_content AND
the disk copy of the managed file is updated so source_location bytes
match. Ambiguous matches (zero or >1 candidate) are left alone here;
Crosswalk surfaces them.
"""
from __future__ import annotations

import base64
import hashlib
import re as _re
from pathlib import Path
from typing import Iterable

from target_record import (
    DeploymentCollection,
    EnvironmentBinding,
    FileComposition,
    TargetRecord,
)


_FEATURE_ID: str = "EPIC-008-F-012"
_BASE64_PREFIX: str = "__base64__:"

# disposition is 'managed' only for files whose bytes the JSON owns
# verbatim per the operator compromise: Dockerfile.
_MANAGED_HANDLER_TYPES: frozenset[str] = frozenset({"dockerfile"})

# Standard exclude set applied to every directory walk. Workflow rsync
# uses the same skip set (__pycache__, *.pyc, .env). Build outputs and
# caches are also dropped so the brain artifact reflects source, not
# generated bytes.
_EXCLUDE_DIRS: frozenset[str] = frozenset({
    "__pycache__",
    "node_modules",
    "dist",
    ".pytest_cache",
    ".vite",
    ".wrangler",
    "bin",
    "obj",
    "out",
    ".git",
    # ArchitectureDesignAndAuditDocs is the standard human-readable
    # design-docs subdir under every feature dir. Contents are docx /
    # md / pptx for human consumption — not deployable, sometimes
    # gitignored (Archive/), so a Linux snapshot of origin/<branch>
    # won't have them, and Crosswalk would REJECT presence checks.
    "ArchitectureDesignAndAuditDocs",
    # Code/Shared/ops is operator dev-time tooling (build/deploy
    # helpers, certs, audit scripts, planning utilities). Nothing in
    # it is imported by any runtime path on any deployed target, so
    # the wholesale-subtree mechanism that staged Code/Shared into
    # the FindCare HF build context was shipping it as dead bytes
    # (BUG-011 surfacing example). REQ-B-010: manifest is exact-truth
    # for files shipped.
    "ops",
})
_EXCLUDE_FILE_NAMES: frozenset[str] = frozenset({".env", ".DS_Store"})
# Operator dev tools and diagnostics that never belong in a deploy
# package (HF Spaces reject >10MB binaries; .log files are local
# runtime output, not source). When operators store such artifacts
# under tools/ subdirs, the Builder must skip them so the JSON's
# files[] enumerates source only.
_EXCLUDE_FILE_SUFFIXES: frozenset[str] = frozenset({
    ".pyc", ".pyo",
    ".exe", ".dll", ".pdb",
    ".log",
    # Operator-local secrets and intermediate cert artifacts. *.crt are
    # public PEMs and stay tracked; everything below is gitignored, so
    # the origin/<branch> snapshot on the remote runner cannot see them
    # and Crosswalk REJECTs the source_location presence check if the
    # Builder enumerates them locally.
    ".key", ".csr", ".enc", ".srl",
})


def _classify_handler(rel_posix: str, name: str) -> str:
    """Map a file to one of the schema's closed handler_type enums."""
    if name == "Dockerfile":
        return "dockerfile"
    if name == "requirements.txt":
        return "python_requirements"
    suffix = Path(name).suffix.lower()
    if suffix == ".py":
        if name.startswith("test_") or name.endswith("_test.py") or "/tests/" in rel_posix:
            return "python_test"
        return "python_source"
    if suffix == ".sh":
        return "shell_script"
    if suffix == ".bat":
        return "bat_script"
    if suffix == ".md":
        return "markdown"
    if suffix in (".json", ".jsonl"):
        return "json"
    if suffix in (".crt", ".key", ".csr", ".pem", ".srl"):
        return "cert_or_key"
    # Everything else (.tsx, .ts, .css, .html, .svg, .png, .pdf, .txt, etc.)
    return "static_asset"


def _disposition_for(handler_type: str) -> str:
    return "managed" if handler_type in _MANAGED_HANDLER_TYPES else "referenced"


def _render_dockerfile(layout: list) -> str:
    """Render an ordered instruction list into Dockerfile text.

    layout = [{"instruction": "FROM", "args": ["python:3.12-slim"]}, ...]
    Each entry becomes one line: '<instruction> <args joined by space>\\n'.
    Comments are not preserved by V1 encoding; layout is the spec.
    """
    if not isinstance(layout, list):
        raise TypeError(f"Dockerfile layout must be a list, got {type(layout).__name__}")
    lines: list[str] = []
    for step in layout:
        if not isinstance(step, dict):
            raise TypeError(f"Dockerfile layout step must be a dict, got {step!r}")
        inst = step.get("instruction")
        args = step.get("args", [])
        if not isinstance(inst, str):
            raise ValueError(f"Dockerfile step missing instruction: {step!r}")
        if not isinstance(args, list):
            raise TypeError(f"Dockerfile step args must be a list: {step!r}")
        if inst == "BLANK":
            lines.append("")
            continue
        lines.append(f"{inst} {' '.join(str(a) for a in args)}".rstrip())
    return "\n".join(lines) + "\n"


def _read_managed_content(abs_path: Path) -> str:
    """Capture bytes for a managed file as a schema-compatible string.

    Try utf-8 strict decode; on failure base64-encode and prefix. Any
    I/O error raises.

    Text content is line-ending-normalized to LF. The JSON is the
    canonical truth; Linux deploy targets receive LF; Windows operator
    working trees (where autocrlf injects CRLF on checkout) get the
    LF version materialized by Extractor on the next V18 gate. Without
    this normalization, embedded_content would alternate between LF
    and CRLF depending on which platform happened to run Builder
    most recently — a permanent source of false-positive drift.
    """
    raw = abs_path.read_bytes()
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError:
        return _BASE64_PREFIX + base64.b64encode(raw).decode("ascii")
    if text.encode("utf-8") != raw:
        return _BASE64_PREFIX + base64.b64encode(raw).decode("ascii")
    # Canonical line-ending normalization: CRLF / lone CR → LF.
    return text.replace("\r\n", "\n").replace("\r", "\n")


def _rel_posix(repo_root: Path, abs_path: Path) -> str:
    return abs_path.relative_to(repo_root).as_posix()


def _walk(
    repo_root: Path,
    dir_rel: str,
    extra_exclude_rel_prefixes: Iterable[str] = (),
) -> list[Path]:
    """Walk repo_root/dir_rel, yielding regular files in deterministic
    order, respecting the standard exclude set plus any extra rel-path
    prefixes the caller wants dropped (e.g., the pre-built React dist
    that lives under backend/static/).
    """
    root = repo_root / dir_rel
    if not root.is_dir():
        raise FileNotFoundError(
            f"Builder expected directory at {root}; absent on disk"
        )
    extra = tuple(p.replace("\\", "/").rstrip("/") for p in extra_exclude_rel_prefixes)
    out: list[Path] = []
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        parts = set(path.parts)
        if parts & _EXCLUDE_DIRS:
            continue
        if path.name in _EXCLUDE_FILE_NAMES:
            continue
        if path.suffix.lower() in _EXCLUDE_FILE_SUFFIXES:
            continue
        rel = _rel_posix(repo_root, path)
        if any(rel == p or rel.startswith(p + "/") for p in extra):
            continue
        out.append(path)
    return out


class Builder:
    """Builds a `DeploymentCollection` by scanning the live tree.

    For files whose handler_type is in `_MANAGED_HANDLER_TYPES`
    (dockerfile), the Builder DOES NOT read bytes
    from disk. Instead, it loads the prior brain artifact and looks
    up the file's `layout` spec, then renders it via the canonical
    renderer (`_render_dockerfile`). The
    rendered string becomes embedded_content. The disk file is
    treated as a downstream materialization, not a source.

    This makes the JSON's `layout` the single source of truth for
    every managed file's bytes. Operators edit the layout in JSON;
    the renderer is the only writer of the rendered text.
    """

    def __init__(self) -> None:
        self._unclassified: list[str] = []
        self._prior_layouts: dict[str, object] = {}

    def unclassified(self) -> list[str]:
        return list(self._unclassified)

    def _load_prior_layouts(repo_root: Path) -> dict[str, object]:
        """Read the prior brain artifact's `layout` for each managed
        file. Returns {source_location: layout}. Absent artifact or
        absent layouts yield an empty dict.
        """
        import json as _json
        artifact = (
            repo_root / "brain" / "machine_artifacts" / "content"
            / "deployment_architecture.json"
        )
        if not artifact.is_file():
            return {}
        try:
            data = _json.loads(artifact.read_text(encoding="utf-8"))
        except Exception:
            return {}
        out: dict[str, object] = {}
        for r in data.get("DeploymentTargetRecord", []):
            for f in r.get("files", []):
                if (
                    f.get("disposition") == "managed"
                    and f.get("handler_type") in _MANAGED_HANDLER_TYPES
                    and "layout" in f
                ):
                    out[f["source_location"]] = f["layout"]
        return out

    def _compose_file(self, repo_root: Path, abs_path: Path) -> FileComposition:
        rel = _rel_posix(repo_root, abs_path)
        name = abs_path.name
        handler = _classify_handler(rel, name)
        disposition = _disposition_for(handler)
        embedded: str | None = None
        layout: object | None = None
        content_hash: str | None = None
        if disposition == "managed":
            if handler in _MANAGED_HANDLER_TYPES:
                layout = self._prior_layouts.get(rel)
                if layout is None:
                    raise RuntimeError(
                        f"Builder: managed {handler} {rel!r} has no layout in "
                        f"the prior brain artifact. Layout is the operator-"
                        f"authored source of truth; run _oneshots/encode_layouts.py "
                        f"to bootstrap a layout from the current disk file."
                    )
                embedded = _render_dockerfile(layout)  # type: ignore[arg-type]
            else:
                embedded = _read_managed_content(abs_path)
        else:
            # disposition='referenced': hash the disk bytes so Crosswalk
            # can detect drift between commit-time and deploy-time content.
            # Exception: the deployment_architecture.json manifest hashes
            # ITSELF — Builder writes new hashes into it after this step,
            # so the stored hash never matches the post-write file content.
            # Skip the self-referential case.
            if rel == "brain/machine_artifacts/content/deployment_architecture.json":
                content_hash = None
            else:
                # CRLF→LF normalize so Windows local + Linux CI compute the
                # same SHA256. autocrlf=true on Windows = CRLF on disk;
                # CI checkouts get LF. The repo's canonical bytes are LF.
                raw = abs_path.read_bytes().replace(b"\r\n", b"\n")
                content_hash = hashlib.sha256(raw).hexdigest()
        return FileComposition(
            feature_id=_FEATURE_ID,
            source_location=rel,
            handler_type=handler,
            disposition=disposition,
            embedded_content=embedded,
            layout=layout,
            content_hash=content_hash,
        )

